### ISSUE TITLE
Won't compile with pre-memcached_touch libmemcached versions

### ISSUE THREAD

**Issue by ketralnis** [lericson/pylibmc#119]
`memcached_touch` looks to have been introduced in this bzr version: https://bazaar.launchpad.net/~tangent-trunk/libmemcached/1.2/revision/929.1.285#libmemcached/touch.cc

Fortunately [the pylibmc code that uses it](https://github.com/lericson/pylibmc/commit/e5c23cce6d8b190f0ba7eb558e963ee6f05db69a) is self-contained enough that it can just be `ifdef`d out with the right `LIBMEMCACHED_VERSION_HEX`

**Comment by lericson** [comment]
So this is fixed I guess
