### ISSUE TITLE
Replace the pools with concurrent.futures

### ISSUE THREAD

**Issue by omerzimp** [lericson/pylibmc#163]
There's no reason to write use them if you have a [ThreadPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html#threadpoolexecutor) built into the python standard and [backported](https://pypi.python.org/pypi/futures) to run on Python 2.x.
This will allow us to remove some code which is always good.
What do you think?

**Comment by lericson** [comment]
I don't understand how `ThreadPoolExecutor` replaces our pooling helpers. Also this is six years old.
