### ISSUE TITLE
time arg does not work in delete() and multi_delete()

### ISSUE THREAD

**Issue by seperman** [lericson/pylibmc#169]
Hello,
Setting time in delete and multi_delete functions raise error in Pylibmc 1.3.0.
`TypeError: 'time' is an invalid keyword argument for this function`

and if I set it as argument:
`TypeError: delete() takes exactly 1 argument (2 given)`

The docs say I should be able to use time in delete(). What's the deal?
Thanks,
Eras

**Comment by jhausauer-kanerai** [comment]
Here is a repro:

```
import pylibmc
print pylibmc.__version__
print pylibmc.libmemcached_version
mc = pylibmc.Client(['localhost:11211'])
mc.set('test_key', 'test_data')
mc.delete('test_key', time = 10)
```

And the output:

```
1.5.0
1.0.18
Traceback (most recent call last):
  File "repro.py", line 6, in <module>
    mc.delete('test_key', time = 10)
TypeError: delete() takes no keyword arguments
```

It fails also if time is passed as a positional argument:

`mc.delete('test_key', 10)`

```
Traceback (most recent call last):
  File "repro.py", line 6, in <module>
    mc.delete('test_key', 10)
TypeError: delete() takes exactly 1 argument (2 given)
```

**Comment by jhausauer-kanerai** [comment]
It is clear from

https://github.com/lericson/pylibmc/blob/master/src/_pylibmcmodule.c#L1428

that the time argument is ignored and 0 is passed to memcached_delete.

**Comment by jhausauer-kanerai** [comment]
I have attempted a patch but found that libmemcached-1.0.18 does not support expiration.

```
1.5.100-dev
1.0.18
Traceback (most recent call last):
  File "repro.py", line 8, in <module>
    mc.delete(key, 4)
pylibmc.Error: error 38 from memcached_delete(test_key): (0xda05b0) INVALID ARGUMENTS, Memcached server version does not allow expiration of deleted items -> libmemcached/delete.cc:159
```

**Comment by jhausauer-kanerai** [comment]
After reading the libmemcached docs, I realized the delete command is actually much less useful than I thought. From docs/source/memcached_delete.rst:

> Expiration works by placing the item into a delete queue, which means that
> it won't be possible to retrieve it by the "get" command. The "add" and 
> "replace" commands with this key will also fail (the "set" command will 
> succeed, however). After the time passes, the item is finally deleted from server memory.

So apparently, the item appears deleted to clients immediately after setting the expiration. I thought that the item would remain accessible for the given time.

**Comment by lericson** [comment]
What an odd feature. I think the story is that the time argument used to exist, was never removed from documentation, but subsequently removed as a feature due to it not working as you noticed.

What do you think is the right way to go here? Remove it from the documentation as well?

**Comment by jhausauer-kanerai** [comment]
Yeah, I agree that it should be removed from the documentation.

On Mon, Mar 14, 2016 at 5:18 AM, Ludvig Ericson <notifications@github.com>
wrote:

> What an odd feature. I think the story is that the time argument used to
> exist, was never removed from documentation, but subsequently removed as a
> feature due to it not working as you noticed.
>
> What do you think is the right way to go here? Remove it from the
> documentation as well?
>
>
> > On 7 mars 2016, at 23:55, jhausauer-kanerai <notifications@github.com>
> wrote:
> >
> > After reading the libmemcached docs, I realized the delete command is
> actually much less useful than I thought. From
> docs/source/memcached_delete.rst:
> >
> > Expiration works by placing the item into a delete queue, which means
> that
> > it won't be possible to retrieve it by the "get" command. The "add" and
> > "replace" commands with this key will also fail (the "set" command will
> > succeed, however). After the time passes, the item is finally deleted
> from server memory.
> >
> > So apparently, the item appears deleted to clients immediately after
> setting the expiration. I thought that the item would remain accessible for
> the given time.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lericson/pylibmc/issues/169#issuecomment-196215799>.
>

-- 

This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee, you should not 
disseminate, distribute, alter or copy this e-mail. Please notify the 
sender immediately by e-mail if you have received this e-mail by mistake 
and delete this e-mail from your system. E-mail transmissions cannot be 
guaranteed to be secure or without error as information could be 
intercepted, corrupted, lost, destroyed, or arrive late or incomplete. The 
sender, therefore, does not accept liability for any errors or omissions in 
the contents of this message which arise during or as a result of e-mail 
transmission. If verification is required, please request a hard-copy 
version. This message is provided for information purposes and should not 
be construed as a solicitation or offer to buy or sell any securities or 
related financial instruments in any jurisdiction.
