### ISSUE TITLE
ThreadMappedPool not working under Python3

### ISSUE THREAD

**Issue by hongyuan1306** [lericson/pylibmc#174]
The bottom of pools.py read:

```python
# This makes sure ThreadMappedPool doesn't exist with non-thread Pythons.                   
try:
    import thread
except ImportError:
    ThreadMappedPool = None
```

This causes ThreadMappedPool to be None under Python 3 since Python3 has renamed thread module to _thread.

Suggested patch:

```python
try:
    import thread
except ImportError:
    try:
        import _thread as thread
    except ImportError:
        ThreadMappedPool = None
```

**Comment by david-berthelot** [comment]
I am having the same problem, could someone apply this patch and make an official release?

**Comment by lericson** [comment]
Will take a look, at the very least this should have blown up in the tests. There seems to be no test coverage for thread-mapped pools. Odd!

**Comment by lericson** [comment]
Ah, line 28 in `tests/test_pools.py`:

```python
# TODO Thread-mapped pool tests
```

**Comment by lericson** [comment]
Alright, got a failing test. Applying the fix and pushing, I'll get back to you. I'll make a new release as soon as I see that the builds pass.
