### ISSUE TITLE
ThreadMappedPools set to None due to 'import thread' fail on Py3

### ISSUE THREAD

**Issue by bastiaan85** [lericson/pylibmc#175]
At the bottom of pools.py, ThreadMappedPools is set to None if Python is deemed not thread-supportive:

```python
    # This makes sure ThreadMappedPool doesn't exist with non-thread Pythons.
    try:
        import thread
     except ImportError:
        ThreadMappedPool = None
```

As noted on the top of the [2.x documentation](http://docs.python.org/2/library/thread.html) for `thread`, it is stated that in Py3 `thread` has been renamed to `_thread`, thereby always breaking ThreadMappedPools in pylibmc on Py3.

**Comment by lericson** [comment]
Fixed in master, will make release soon!
