### ISSUE TITLE
can not increase a key does not exists in the memcached?

### ISSUE THREAD

**Issue by zj8487** [lericson/pylibmc#178]
i need a counter to record the object count. and increase 
the counter once the object is created.

i tried it, but it says as follow:

```
In [35]: print(mc.incr("test_key"))
---------------------------------------------------------------------------
NotFound                                  Traceback (most recent call last)
<ipython-input-35-7d26c05fcf43> in <module>()
----> 1 print(mc.incr("test_key", 0))

NotFound: 1 keys not found
```

**Comment by lericson** [comment]
That is in fact the semantics of incr in memcached. I can offer no meaningful rationale, sorry.

- Ludvig (phone)

**Comment by zj8487** [comment]
thanks a lot.
now i tried as follow every time and it works:
```
mc.add("test_key", 0)
mc.incr("test_key")
```

is memcached has an api like ```incr_with_init(key, value)```: increase the key when it is exists and if not set the valuse?
