### ISSUE TITLE
pylibmc.ThreadMappedPool is None in v1.4.1

### ISSUE THREAD

**Issue by halfak** [lericson/pylibmc#181]
$ python
    Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
    [GCC 4.8.2] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pylibmc
    >>> type(pylibmc.ThreadMappedPool)
    <class 'NoneType'>
    >>> pylibmc.__version__
    '1.4.1'

It looks like the issue is in the last lines of https://github.com/lericson/pylibmc/blob/00ac0c9b202ea7bff0e212ecc5f0964261782966/src/pylibmc/pools.py

It doesn't look like the last commit in the repo has solved the issue, so a releasing a new version should fix the problem.

**Comment by lericson** [comment]
That's not good! I guess we should use `_thread` then, it exists on both versions of Python and only when threads are available.

**Comment by lericson** [comment]
ISTM this is fixed in HEAD, no? It uses `threading` and falls back to `dummy_threading`.

**Comment by lericson** [comment]
Will be fixed in the next release.
