### ISSUE TITLE
Memory leak caused by lost references in _key_normalized_obj

### ISSUE THREAD

**Issue by joshuahlang** [lericson/pylibmc#183]
The lines in the *_key_normalized_obj* method which assign a new object to *key cause references to the object to be lost and memory to be leaked. An example follows:

    if (PyUnicode_Check(*key)) {
        *key = PyUnicode_AsUTF8String(*key);
        if (*key == NULL)
            return 0;
    }

If the caller of `_key_normalized_obj` decrements the reference returned in key, the object passed in as the initial value of `*key` will not be decremented. If the caller does not decrement the object reference count, then any object allocated inside of `_key_normalized_obj` will be leaked. The only way this method doesn't seem to lose an object reference is if a bytes (or an invalid object) is passed in and the length is less than the maximum allowed.

**Comment by lericson** [comment]
Does this fix the problem?

**Comment by lericson** [comment]
Also e3d9871

**Comment by joshuahlang** [comment]
That does fix the leaks in that method, but there are others in callers of that method which are non-obvious due to the method's interface (in my opinion). Many callers of *_key_normalized_obj* aren't releasing the reference returned when a new object is allocated by *_key_normalized_obj*. *PylibMC_Client_get* is a good example of this. See below for a simple script which illustrates the memory leak, even with the latest fixes:

    import pylibmc
    mc = pylibmc.Client(["127.0.0.1"], binary=True)
    while True:
        try:
            mc.get(u'foo')
        except:
            pass


I would consider changing *_key_normalized_obj* to return a *PyObject**, with a new reference and require the caller to release that reference. I think that would lessen the likelihood of memory leaks such as these.

**Comment by lericson** [comment]
Oh, I see the problem. It's a rather stupid idea in general this normalizing thing.

**Comment by lericson** [comment]
Hm, now that I think about it I disagree again.

**Comment by lericson** [comment]
After spending a couple of hours on hunting down these memory leaks, I think I fixed most of them for now. Will have to revisit before next release, and put some kind of test in for this.

**Comment by lericson** [comment]
See d52bfba.

**Comment by lericson** [comment]
@hfalcic, there were *a lot* of memory leaks in the Python 3.x unicode-str bridge stuff! What gives?

**Comment by joshuahlang** [comment]
Any idea when an official release with these fixes will be up on pypi?

**Comment by lericson** [comment]
Soon! I want to do some testing first though, I'd like to have a tool to do it actually, as part of the test suite. 

- Ludvig (phone)

**Comment by lericson** [comment]
This has been released. :smile:
