### ISSUE TITLE
num_replicas not working as expected

### ISSUE THREAD

**Issue by rnikoopour** [lericson/pylibmc#185]
Hello,
I'm trying to use the num_replicas behavior to for high availability.  However, no matter what I set num_replicas to I'm only seeing the key stored on one server.

My understanding of this behavior is that it would store the key on N servers as specified by num_replicas.

I tested this in the case of two servers with num_replicas set to 2 with both modulo and consistent hashing.  I always ended up with the key being stored on one server only.

I want to make sure that I'm not misunderstanding what this behavior is supposed to do.

I do the following in Python:
```
>>> import pylibmc
>>> a = pylibmc.Client([sever1, server2], behaviors={'num_replicas': 2})
>>> a.add('akey', 123)
True
```
Then on each server I do the following:
```
telnet localhost 11211
get akey
```
Only one of the servers stores the key and I get the value.  The other server just responds with end.

Thanks

**Comment by rnikoopour** [comment]
Using an old version of pylibmc is the problem.  Closing this.

**Comment by rnikoopour** [comment]
I thought this was a version issue, but using version 1.4.2 I'm still experiencing the same thing.

**Comment by lericson** [comment]
Can't help you, it's a libmemcached issue. Ping @brianaker.
