### ISSUE TITLE
Can't use 'verify_keys' behavior

### ISSUE THREAD

**Issue by connienguyen** [lericson/pylibmc#187]
Hi,

I'm trying incorporate memcached into a project through pylibmc and I'm running into a pylibmc error when trying to set the 'verify_keys' behavior to true. 
```python
>>> mc = pylibmc.Client(['localhost'], binary=True)
>>> mc.behaviors = {
...     'tcp_nodelay' : True,
...     'verify_keys' : True,
...     'ketama' : True
... }
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/Users/hades/Documents/Repos/myproject/venv/lib/python2.7/site-packages/pylibmc/client.py", line 195, in set_behaviors
    return super(Client, self).set_behaviors(_behaviors_numeric(behaviors))
pylibmc.Error: memcached_behavior_set returned 38 for behavior 'verify_keys' = 1
```
I'm using pylibmc 1.4.3

Any ideas on how to fix this would be appreciated. Thanks!

**Comment by lericson** [comment]
The reason is that you can't have `verify_keys` together with `binary`. This should perhaps be made clearer.

**Comment by connienguyen** [comment]
Thanks! I think I was confused by the example in the documentation.

**Comment by lericson** [comment]
Oh, well that certainly needs to be fixed!
