### ISSUE TITLE
Setting "server_max_value_length" when connecting

### ISSUE THREAD

**Issue by gregpinero** [lericson/pylibmc#190]
I'm running memcached with -I 3m option to let it store up to 3 MB values.   

I'm trying to figure out how to specify that to pylibmc.  I tried this:

        self.cache = memcache.Client(servers, binary=True,
            server_max_value_length=(1024 * 1024 * 2),
            behaviors={"tcp_nodelay": True, "ketama": True, "no_block": True})

But I got this:

  File "utils.py", line 63, in __init__
    behaviors={"tcp_nodelay": True, "ketama": True, "no_block": True})
TypeError: __init__() got an unexpected keyword argument 'server_max_value_length'

**Comment by lericson** [comment]
Hm, did you just guess? There's no such thing :)

- Ludvig (phone)

**Comment by gregpinero** [comment]
Yeah, looks like you're right.  I was coming over from the other Python memcached library and I was using that argument on the init there.  I remember reading to do that somewhere.

**Comment by lericson** [comment]
Aha alright, then I understand. Sorry for misunderstanding. What happens if you try to store larger values?

**Comment by gregpinero** [comment]
It seems to work fine for storing larger values.

**Comment by lericson** [comment]
Alright, then I think we can leave things as they are, or what do you think?

**Comment by gregpinero** [comment]
Yeah that's fine with me.

**Comment by lericson** [comment]
Ok, great :+1: -- don't hesitate to shoot me a comment if you need any other help, or stop by `#sendapatch` on freenode!
