### ISSUE TITLE
Images not displaying in Django

### ISSUE THREAD

**Issue by harisbeha** [lericson/pylibmc#192]
When I enable caching, the thumbnail urls on my homepage are not rendered. I believe this is only occurring on pages where I also have django_endless_pagination, although I don't necessarily believe this is the cause. Does anyone know the cause or where to start looking to resolve this issue. Has anyone else had an issue with sections of pages not rendering with pylibmc? 

The page renders just fine when the caching is turned off.

**Comment by harisbeha** [comment]
Additional information: 

- Using latest stable build 
- No errors thrown in server or browser console

**Comment by lericson** [comment]
Does it work with other libraries?

- Ludvig

**Comment by harisbeha** [comment]
It seems to work fine with other libraries. I ended up caching just a fragment of the template and it seems to work fine now. I don't know how I would go about providing any more information about this issue, and it seems I'm the only one that has it.
