### ISSUE TITLE
Add a license to the repo

### ISSUE THREAD

**Issue by mbrukman** [lericson/pylibmc#193]
Could you please add an explicit LICENSE file to the repo so that it's clear under what terms you're providing this code?

Per [GitHub docs on licensing](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license):

> Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.

Thanks!

**Comment by jnordberg** [comment]
The license is in src/LICENSE

**Comment by jnordberg** [comment]
:closed_book:

**Comment by mbrukman** [comment]
Sorry, didn't realize it's located in a subdirectory. It would be nice to either move it to the root directory as it's also typically where the license is found, or if you really prefer to keep it in `src`, please note that in the README.
