### ISSUE TITLE
Pylibmc is missing dependancies for CentOS 6

### ISSUE THREAD

**Issue by markriggins** [lericson/pylibmc#194]
I kept getting installation errors, while trying to install pylibmc on centos6

1) src/_pylibmcmodule.h:42:36: error: libmemcached/memcached.h: No such file or directory
Which means that we need libmemcached-devel

2) After installing libmemcached-devel, I the graduate to this error: 
src/_pylibmcmodule.h:195: error: 'MEMCACHED_BEHAVIOR_TCP_KEEPALIVE' undeclared here (not in a function)

Which shows that our versions are not aligning properly.  I don't want to downgrade pylibmc back to 1.2.3
I found more details here -- http://stackoverflow.com/questions/24437325/pip-unable-to-install-pylibmc

So I needed a `sudo yum install ius-release` followed by 
`sudo yum install libmemcached10 libmemcached10-devel

Now with the libmemcached in sync, I can finally install your package.

It took quite a bit of time to trace down these dependencies.  Please update your setup.cfg

**Comment by lericson** [comment]
I'm not sure what I should change, setup.cfg?

- Ludvig

**Comment by lericson** [comment]
It sounds like you have a very old version in your package manager, is it pre 1.0.0? It says pretty clearly in the documentation which version works.
