### ISSUE TITLE
tcp_keepalive not mentioned in documention

### ISSUE THREAD

**Issue by mlowicki** [lericson/pylibmc#199]

**Comment by lericson** [comment]
What does it do?

**Comment by mlowicki** [comment]
mentioned in https://pypi.python.org/pypi/pylibmc/1.3.0 "Added behaviors tcp_keepalive".

**Comment by lericson** [comment]
Very likely it just enables TCP keepalive if possible.

**Comment by lericson** [comment]
I think it's not worth documenting -- a niche feature to be sure, 99.999% of users won't have the need for it. Is there an underlying reason you opened this issue?

**Comment by mlowicki** [comment]
It's good know that it's available if you're reaching certain scale and avoiding lots of TCP handshakes can reduce contention or stop flooding Memcached with too much connection requests.

**Comment by lericson** [comment]
I think in this case the keepalive would be pretty useless — if you already have lots of data crossing the wire (i.e. you’re heavy on traffic like you say) then keepalive isn’t going to help. Are you confusing this behavior with TCP_NODELAY?

**Comment by mlowicki** [comment]
Let's say you're handling 10k req/s. If every request means contacting Memcached they you would end up establishing lots of new connections per second. Better is to reuse ones already created.

**Comment by lericson** [comment]
I don't understand how that relates to the behavior discussed here, they're unrelated features -- you can avoid reconnecting simply by keeping the same client instance around.

- Ludvig

**Comment by mlowicki** [comment]
If you need to create clients frequently then piggy backing on already created connection could be a huge boost.

I think discussion here took more energy that actually writing patch for documentation which describes f.ex. `tcp_nodelay`. Don't want to waste more time on pushing it so feel free to close it.

**Comment by lericson** [comment]
I agree, it is best to close this issue. I think you just misunderstood what TCP_KEEPALIVE does. It is a TCP-level mechanism that simply tries to prevent connections dropping due to inactivity -- i r to keep them alive.
