### ISSUE TITLE
SEGFAULT from libmemcached

### ISSUE THREAD

**Issue by alecghica** [lericson/pylibmc#205]
We are using the following setup:
- operating system: CentOS 7
- Python: 2.7
- pylibmc: 1.5.0
- libmemcached-1.0.16-5.el7.x86_64
- libmemcached-devel-1.0.16-5.el7.x86_64

Bellow is the gdb trace of the SEGFAULT we get:
- https://gist.github.com/alecghica/85a70186af8a46e23f22

I noticed that the libmemcached version used in tests under https://travis-ci.org/lericson/pylibmc for Python 2.7 is either 0.44, 0.53 or 1.0.8. We downgraded libmemcached to:
- libmemcached-1.0.8-1.x86_64
- libmemcached-devel-1.0.8-1.x86_64

... but the problem persist, same SEGFAULT received.

To me looks like a bug/issue in C code under libmemcached:

`0x00007fd31df6acd6 in _PylibMC_Inflate (
    value=value@entry=0x16565810 "x\234t\275{P\024Y\266/,O\345-\242\264\202\212<T\020\360\201\200\b\n*\n\202h\203o|\240\335>\020\021\265UP\004%\362\265+3we\225^\217\274\033\004\244\032Ji\272\001\233\356\333\031\341\231\313Ä\272\206\061\067\342\213\"\356\371\342\213\357\017\343\326\t\377 \242\303\034f\356\364!\234\210o\255\235\205\335s\276scZ\315\312Ü¹\367Îµ\327\343\267\326^k\217ß\234\277\244\215dn\275\260\347\350\255K\227no,\371\234]\004Ã¿\365\027j/\335\t\376\312gcrr\351g\t\377\063\377hÔµ\005\v\336q\351\226\064\370K\252w\246\022K\262\367\237g+\177\273\325[\314\371\343%\277\226N\022j\355O"..., size=size@entry=585699, result=result@entry=0x7fd31ac9a270,
    result_size=result_size@entry=0x7fd31ac9a278, failure_reason=failure_reason@entry=0x7fd31ac9a280) at src/_pylibmcmodule.c:482`

As I don't have the necessary knowledge can someone please look into this?

For the reference: the original ticket where the issue was addressed if [here](https://taskman.eionet.europa.eu/issues/31739). This is mostly of interest for the Plone users.

**Comment by lericson** [comment]
I'll look into this in a while -- for now, what version of zlib are you running, and how big is the allocation? I'm pretty sure the problem is due to zlib (the crash happens in the inflation routine)

- Ludvig

**Comment by alecghica** [comment]
@lericson zlib in use:
- zlib-devel-1.2.7-15.el7.x86_64
- zlib-1.2.7-15.el7.x86_64

Regarding the allocation I don't know, any ideea how can I get that?

**Comment by lericson** [comment]
I'm basically wondering how big is the string your storing.

**Comment by lericson** [comment]
I looked at where the crash happens, which is supposedly line 482 in _PylibMC_Inflate -- however, line 482 isn't in _PylibMC_Inflate in the 1.5.0 release code. Can you compile the release and see if it still happens?

**Comment by alecghica** [comment]
@lericson we are using pylibmc and memcached from a CMS written in Python, called [Plone](https://plone.org/), to cache all the queries made to the database. In respect to this the strings stored may be quite big. 

We are using the pylibmc version 1.5.0 released on PyPi, under https://pypi.python.org/pypi/pylibmc.
I will try to use pylibmc from sources and let you know.

One question, what is the recommended version of _libmemcached_ to be used for:
- pylibmc 1.5.0
- Python 2.7
- CentOS 7

**Comment by alecghica** [comment]
We also downgraded _libmemcached_ to version 0.53 but the segfault is still there, I'll try now to get pylibmc from sources as you suggested.

**Comment by lericson** [comment]
> We are using pylibmc and memcached from a CMS written in Python, called Plone, to cache all the queries made to the database. In respect to this the strings stored may be quite big.

I think the bug is stemming from the dataset being too large and zlib and/or Python being unable to inflate it (i.e. runs out of memory or is simply denied the allocation.) How is your memory usage when this happens?

> One question, what is the recommended version of libmemcached to be used for:

I think the most recent version in your favorite package manager should be fine.

**Comment by alecghica** [comment]
@lericson I don't know exactly what you had in mind regarding the memory usage but if the memory is not in swap or something out of the ordinary (if this was the answer you looked for). We get segfaults from various contexts and indeed most of them when querying large objects. I suspected also that is has to do datasets too large but is not always the case, it happens on normal queries too sometime.

From the example I added in the issue description (as far as I understand) it states the size _size=size@entry=585699_ ... and this doesn't seems to be a big size. Am I wrong?

Also, right after _value=value@entry=0x16565810 _ there is a string and I suspected that the value/string listed there is doing the crash. As we have a lot of multilingual content I thought it may be some "strange" character or something like that.

**Comment by lericson** [comment]
> On 11 feb. 2016, at 17:01, Alexandru Ghica <notifications@github.com> wrote:
> 
> I don't know exactly what you had in mind regarding the memory usage but if the memory is not in swap or something out of the ordinary (if this was the answer you looked for). We get segfaults from various contexts and indeed most of them when querying large objects. I suspected also that is has to do datasets too large but is not always the case, it happens on normal queries too sometime.

What I mean is I think memory allocations are getting denied, and unallocated pointers are getting written to or freed from. Something is amiss. Which brings me to...

> From the example I added in the issue description (as far as I understand) it states the size size=size@entry=585699 ... and this doesn't seems to be a big size. Am I wrong?
> 
> Also, right after _value=value@entry=0x16565810 _ there is a string and I suspected that the value/string listed there is doing the crash. As we have a lot of multilingual content I thought it may be some "strange" character or something like that.

Right, so the goal right now is to find out which line is actually triggering the crash. L482 isn’t a function call in any release that I can find.

Thanks for being so patient with the bug report!

**Comment by alecghica** [comment]
I put pylibmc from sources (latest on master) and still I could reproduce the SEGFAULT.

I don't know why you say that at L482 there is no function call, as far I can see there is a _free(out);_ call, see: https://github.com/lericson/pylibmc/blob/master/src/_pylibmcmodule.c#L482

>  the goal right now is to find out which line is actually triggering the crash

In respect to the above, I'll get more courage and I'll try to do some debug in the __pylibmcmodule.c_ file and I'll come back with the findings :)

> Thanks for being so patient with the bug report!

I thank you for being so helpful!

**Comment by lericson** [comment]
> I put pylibmc from sources (latest on master) and still I could reproduce the SEGFAULT.
> 
> I don't know why you say that at L482 there is no function call, as far I can see there is a free(out); call, see: https://github.com/lericson/pylibmc/blob/master/src/_pylibmcmodule.c#L482

I was looking at the released code.

> In respect to the above, I'll get more courage and I'll try to do some debug in the __pylibmcmodule.c_ file and I'll come back with the findings :)

Right, so, what we need to know now is why does this free() fail? We can inspect this with two variables, the is latter especially useful:

1. Is `rc` not `Z_OK`?
2. What is `failure_reason`?

So how do you inspect these? Well, for one you could simply add prints to these lines and catch them in a log. Or, if you can reproduce this error reliably, you can run the Python interpreter under `gdb` or `lldb` and inspect the program stack. It’s as simple as `p rc` and `p failure_reason`.

**Comment by alecghica** [comment]
I just added some prints to find the values of _rc_ and _Z_OK_ and in all cases both are 0 except for the case when segfault occur when they have the following values:
- rc: -4
- Z_OK: 0

The _failure_reason_ is always an empty string.

**Comment by lericson** [comment]
Just as I suspected then, from my local `zlib.h`:

    #define Z_MEM_ERROR    (-4)

**Comment by lericson** [comment]
Are you sure it's an empty string? It isn't a NULL pointer? Keep in mind that `failure_reason` is a double pointer -- to know what it's pointing at, you need to look at `*failure_reason`.

**Comment by alecghica** [comment]
I did something wrong in C code regarding the printing (I am just a Python programmer :)). Update:

When segfault occur the value of _failure_reason_ is _realloc_.

**Comment by alecghica** [comment]
@lericson any updates on this? There is any more info I may send to help settle this out?

**Comment by lericson** [comment]
I tried re-creating the crash, but I was unsuccessful. Maybe if you could submit a minimal reproduction case, I could fix the bug!

- Ludvig

**Comment by alecghica** [comment]
@lericson will be quite hard (if not impossible) for me to create a minimal reproduction case for a simple pylibmc usecase as we use it inside a quite complex stack here with a CMF + CMS etc.

What I can do and I think is the best, I can give you access to the host where I have it in use (in a devel environment, is not a production machine) and give you details on how to easily reproduce the segfault. All I need from you is a public SSH key. The pylibmc there is from sources (master) directly. Do you think it fit to do so?

**Comment by alecghica** [comment]
Thx @lericson! I can confirm the SEGFAULT issues described in this ticket is fixed/handled.
