### ISSUE TITLE
Possibility to know which host a particular key will be mapped to?

### ISSUE THREAD

**Issue by mnjul** [lericson/pylibmc#207]
Well, I am into a quite sizable use case, with several dozens of memcached server instances acting as a distributed cache (i.e. a list of server 'hostname:port' passed into pylibmc Client constructor).

I have been debugging into an issue that requires me to know which host a specific key is mapped to. Is there any way this may be achieved in pylibmc, like hacking into its code and expose the information through an added method? Or I have to dig into libmemcached?

Any light-shedding would be greatly appreciated.

As a side note... under my current scenario I am not using any kind of ketama / consistent hashing and I am not utilizing the failover mechanism. I'm expecting that, assuming the list of servers are kept the same and the underlying libmemcached is acting sane (no rhyme intended), a key will always be mapped to the same host, right?

**Comment by lericson** [comment]
Sadly, this is more complicated than it perhaps should be. However, if you're using the default settings I think memcached uses `servers[crc32(key) % len(servers)]`

**Comment by mnjul** [comment]
Thanks for the answer. I'll give it a shot. Almost thinking I should use a network packet sniffer (facepalm)
