### ISSUE TITLE
Failover not working?

### ISSUE THREAD

**Issue by Jasim9** [lericson/pylibmc#214]
I am using pylibmc 1.5.1, and I have this simple script to check failover in pylibmc:

```
import pylibmc, time

def main():
        mc=pylibmc.Client(["192.168.1.25:11211","192.168.1.29:11211","192.168.1.30:11211","192.168.1.31:11211"],behaviors={"distribution":"consistent"})
        mc.behaviors['ketama'] = True
        mc.behaviors['remove_failed'] = 1
        mc.behaviors['retry_timeout'] = 1
        mc.behaviors['dead_timeout'] = 1

        print pylibmc.__version__

        for i in range(1,5):
                mc.set("test%d"%i,"value%d"%i)
                time.sleep(1)

        for i in range(1,5):
                mc.get("test%d"%i)
                time.sleep(1)


main()

```
I have 4 machines with memcached installed and running on them, if all 4 are up and running then the script runs fine. But if I take down one, before starting the experiment or in the middle of experiment, I get the following Exception/error:

pylibmc.ConnectionError: error 3 from memcached_get(test4): (42056576) CONNECTION FAILURE, ::rec() returned zero, server has disconnected, host: 192.168.1.29:11211 -> libmemcached/io.cc:456

I have set the behaviors for failover as can be seen in code.
I was expecting the set and get will automatically adjust to the changes at server side and work around the failure.
I checked, the keys are not set either in memcached either.

**Comment by Jasim9** [comment]
Okay I think I got it. I increased the dead_timeout to 60, and now the requests fail only at 60 second intervals. So this means that failover is not transparent as it is in PHP-memcached. It would be a nice feature to have transparent failover support where client automatically handles the server dead and sends the request to another server which is not dead.

**Comment by lericson** [comment]
Cool bananas.

I want this as well but it is up to the libmemcached people to implement, and us to enjoy if they so choose.

Happy hacking!
