### ISSUE TITLE
server weight in type unix

### ISSUE THREAD

**Issue by espectro** [lericson/pylibmc#215]
How to transfer the weight of the server in pattern for type unix?

 > import pylibmc
 > c = pylibmc.Client(["/var/run/memcached1.sock", "/var/run/memcached2.sock"])

If use anti-pattern for convenience:

> import pylibmc
> c = pylibmc.Client([(4, "/var/run/memcached1.sock", 0) , (4, "/var/run/memcached2.sock", 0)])

https://github.com/lericson/pylibmc/blob/master/src/pylibmc/client.py#L83
wherefore?  len(server) == 3:

**Comment by lericson** [comment]
Because it's really, really niche. People don't run multiple memcached servers on the same machine; there's no point.
