### ISSUE TITLE
[Regression] Pickle no longer using the highest protocol

### ISSUE THREAD

**Issue by BertrandBordage** [lericson/pylibmc#216]
This was working using pylibmc 1.5.0 with Python 2.7, but no longer works on version 1.5.1:
```python
import pylibmc

class UnpickableType(object):
    __slots__ = ('a',)

mc = pylibmc.Client(['/tmp/memcached.sock'])
mc['test'] = UnpickableType()
```
But it works using Python 3.
That’s because pylibmc now seems to use the default pickle protocol instead of the highest available protocol.

**Comment by BertrandBordage** [comment]
This commit seems to be the problem: https://github.com/lericson/pylibmc/commit/e668304f9ed3c9146bf6cd7663bf012045726e26
I guess `-1` means “highest protocol” while `NULL` means “default protocol”.

**Comment by lericson** [comment]
Damn, guess that has to be fixed.

**Comment by thebostik** [comment]
I just came across this. Could it be worth releasing a patch version with this fix included due to the better speed and decreased output size of the higher protocols?

**Comment by kaisen** [comment]
+1

**Comment by lericson** [comment]
I done did it

**Comment by pawl-rs** [comment]
Could this cause any backwards compatibility issues with stuff cached using previous versions of pylibmc?

**Comment by lericson** [comment]
@pawl-rs Yes, see #235 above.

**Comment by lericson** [comment]
I have introduced a behavior to remedy this. See my latest comment in #235.
