### ISSUE TITLE
"Assertion `memcached_failed(rc)' failed." with libmemcached 1.0.8

### ISSUE THREAD

**Issue by edmorley** [lericson/pylibmc#218]
Is the assertion/abort (not the earlier exceptions) something that pylibmc could/should be handling better? Or just a bug in older versions of libmemcached/memcached server that can't be worked around?

```
$ python -m pylibmc
...
>>> mc.set('key with spaces', 'value')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
SocketCreateError: error 11 from memcached_set: SUCCESS
>>> mc.flush_all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
SomeErrors: error 19 from flush_all: SUCCESS
>>> mc.set('a-valid-key', 'value')
python: libmemcached/storage.cc:341: memcached_return_t memcached_send_ascii(memcached_st*, memcached_server_write_instance_st, const char*, size_t, const char*, size_t, time_t, uint32_t, uint64_t, bool, bool, memcached_storage_action_t): Assertion `memcached_failed(rc)' failed.
Aborted
```

Using:
- Ubuntu 14.04 x64
- Python 2.7.12 (third-party ppa: fkrull/deadsnakes-python2.7)
- The distro's latest memcached server release (1.4.14)
- The distro's latest libmemcached release (1.0.8)
- pylibmc 1.5.1

The assertion didn't repro when I tried using Ubuntu 16.04, whose package repository has the newer memcached server 1.4.25 and libmemcached 1.0.18.

**Comment by lericson** [comment]
Sadly we work around `abort()` calls in C unless we know beforehand that the function is going to trigger an abort -- in which case the fix is to not call the function. It sounds like libmemcached should absolutely not be triggering aborts though.
