### ISSUE TITLE
Invalid keys don't always result in an exception when using verify_keys

### ISSUE THREAD

**Issue by edmorley** [lericson/pylibmc#219]
In #114 one suggested workaround was to enable the `verify_keys` behavior option.

However this seems to behave inconsistently depending on the nature of the invalid key:

```
$ python -m pylibmc
...
>>> mc.set_behaviors(dict(verify_keys=True))
>>> mc.set('key with spaces', 'value')
False
>>> mc.set('a'*251, 'value')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ValueError: key length 251 too long, max is 250
```

(Using Ubuntu 14.04, Python 2.7.12, distro libmemcached 1.0.8, pylibmc 14f66d7).

Expected:
If `verify_keys=True` is set, and an invalid key is specified - then regardless of the way in which the key was invalid, pylibmc should either:
- always raise an Exception
- always return False

Compare this to when not using `verify_keys` - both of the examples above raise (albeit the 'key with spaces' one also screws with the server for a few seconds, but anyway). In addition, when using python-memcached both cases raise (`memcache.MemcachedKeyCharacterError` and `memcache.MemcachedKeyLengthError` respectively).

It would be good to also document the expected behavor (once fixed or wontfixed) under the `verify_keys` section on:
http://sendapatch.se/projects/pylibmc/behaviors.html
(and maybe also worth mentioning that `verify_keys` can't be used alongside binary mode)
...I'm happy to open a PR for the docs part at some point.

**Comment by edmorley** [comment]
Could you confirm whether this behaviour is expected, or a bug?

**Comment by lericson** [comment]
When I checked python-memcache's behavior, they were basically ignoring errors or returning None as if the key was unset. It seems that has changed. What do you think is the proper way to go forward?
