### ISSUE TITLE
MEMORY ALLOCATION FAILURE for touch(-1) when Binary=False

### ISSUE THREAD

**Issue by niconoe** [lericson/pylibmc#220]
The title says it all:

    import pylibmc

   mc = pylibmc.Client(["127.0.0.1"], binary=False)

   mc["mykey"] = "Some value"
   mc.touch("mykey", -1)

Triggers: `Traceback (most recent call last):
  File "montest.py", line 6, in <module>
    mc.touch("mykey", -1)
_pylibmc.AllocationError: error 17 from memcached_touch(mykey): (0x2380b30) MEMORY ALLOCATION FAILURE(Cannot allocate memory), Error occcured while writing touch command to server,  host: 127.0.0.1:11211 -> libmemcached/touch.cc:146`

But only if binary=False.

This has been tested with pylibmc 1.5.1 on:
- Mac OS X 10.10.5, with libmemcached 1.0.18 and memcached 1.4.33
- Ubuntu 15.04 with libmemcached 1.0.18 and memcached 1.4.14

**Comment by lericson** [comment]
Not our fault, contact the libmemcached people. Cheers!
