### ISSUE TITLE
The 1.5.1 release changes are listed under 1.5.0

### ISSUE THREAD

**Issue by edmorley** [lericson/pylibmc#222]
The changelog's last listed version number is 1.5.0, rather than the latest release (1.5.1).

It looks like the 1.5.1 changes were added under 1.5.0 instead:
https://github.com/lericson/pylibmc/compare/1.5.0...1.5.1

**Comment by lericson** [comment]
Intentional

**Comment by edmorley** [comment]
Could you change the "1.5.0" heading to say "1.5.0/1.5.1" instead?
This is very confusing otherwise (and inconsistent with all other changelogs).

**Comment by edmorley** [comment]
Or alternatively something like "1.5.x series".

**Comment by lericson** [comment]
That would probably be a good idea
