### ISSUE TITLE
Publish a manylinux wheel to pypi

### ISSUE THREAD

**Issue by bxm156** [lericson/pylibmc#225]
It would great if a manylinux wheel could be published to pypi for this project. For more information about [manylinux, see PEP 513](https://www.python.org/dev/peps/pep-0513)

Many linux allows for users to use pylibmc on the majority of linux platforms (regardless of version), without having to deal with binary dependencies. (Which is useful for server deployments to AWS Lambda for example).

The basic idea is to add some lines to the travis.yaml file, which can build and deploy a manylinux wheel to pypi.  This uses a special image to build the wheel and link in the binary dependencies.  (See https://github.com/pypa/python-manylinux-demo for another example and more info). Special docker images from a PyPA repo are used to build a wheel that will work on almost any linux system.

I wrote an example of what this would look like at https://github.com/bxm156/pylibmc-manylinux . The wheels can be downloaded at: https://github.com/bxm156/pylibmc-manylinux/releases.
I'm using the above wheels in my own projects.

**Comment by tspecht** [comment]
Any chance we could get this in? Want to use pylibmc on Lambda and can't currently since the libmemcached-dev headers are not installed.

**Comment by lericson** [comment]
I did a wheelie

☸️
