### ISSUE TITLE
How to configure Failover, must i use the recommended failover behaviors?

### ISSUE THREAD

**Issue by awesome-tao** [lericson/pylibmc#226]
official doucument like this:
mc.behaviors['ketama'] = True
mc.behaviors['remove_failed'] = 1
mc.behaviors['retry_timeout'] = 1
mc.behaviors['dead_timeout'] = 60

i use django and have 2 memcached servers, 
resent days one of my memcached is always error, like:
**1.error 31 from memcached_add: (0x6b0fb80) A TIMEOUT OCCURRED, No active_fd were found
2.ServerDead: error 35 from memcached_set: SERVER IS MARKED DEAD**

my configuration like this 
`'{
            "tcp_nodelay": True,
            "hash": "murmur",
            "distribution": "consistent",
            "failure_limit": 1,
            "dead_timeout": 60,
            "remove_failed": 1,
            "no_block": True,
}'
`
and the failover is not work for me, how should i do?  Thank you for answering my question！

**Comment by lericson** [comment]
How do you know it always fails? Probably fails intermittently or the client is being recreated every time.

**Comment by ivictbor** [comment]
Noticing it from time to time, very random. Using Django plus 8-threaded gunicorn

```
ylibmc.Error: error 31 from memcached_get(:1:views.decorators.cache.cache_): (0x561eab2df870) A TIMEOUT OCCURRED, No active_fd were found,  host: memc_ssr:11211 -> libmemcached/io.cc:259
```

**Comment by lericson** [comment]
Sounds like intermittent network issues, not really something we can fix. Failover triggers after a failure.
