### ISSUE TITLE
failover policy

### ISSUE THREAD

**Issue by gote2017** [lericson/pylibmc#228]
Hi

We are using the pylibmcp pool: ylibmc.ClientPool(mc=None, n_slots=0) (release 1.5.2)

In the client init we use the behavior (including recommended failover policy):
'tcp_nodelay': True,
'verify_keys': True,
'ketama': True,
 'remove_failed': 1,
'retry_timeout': 1,
'dead_timeout': 60

There is a firewall in the system wich kills the memcache connections when they are not being used for a configured time. After that, when the process uses a connection again then the failover process starts.

Is it possible a failover behaviour more agile? The process needs to reuse some times the connection to complete the failover process and recover the connection.

Thanks a lot

**Comment by lericson** [comment]
Not a bug it seems. Come talk to us in `#sendapatch` instead. If your firewall resets the connection it should probably be sending a TCP RST and trigger a connection close.
