### ISSUE TITLE
Docs on `.touch()` are not accurate

### ISSUE THREAD

**Issue by SeanColombo** [lericson/pylibmc#232]
The current docs imply that the second parameter will increase the expiration by a number of seconds.

Rather, they set the expiration to that many seconds (or to that timestamp if the number is greater than 24*60*60*30) which is standard memcache behavior and also what pylibmc does.

```

**Comment by lericson** [comment]
Duplicate of #233

**Comment by SeanColombo** [comment]
For posterity... this was fixed here: https://github.com/lericson/pylibmc/commit/c1e50df8297e1edad9d7f9a249a42f9bb2a18d71
