### ISSUE TITLE
Strange encoding used by pylibmc 1.5.2

### ISSUE THREAD

**Issue by Antoine-B2** [lericson/pylibmc#234]
Hello,

The encoding used by pylibmc is not compatible with other clients or with the memcached server. Therefore command `incr` will fail. I tried with pylibmc 1.5.2 on an archlinux and on an Ubuntu and the error is the same.

Here's a snippet of some test code :
```
import pylibmc
ip = "192.168.13.56"

print(pylibmc.__version__)

tcp = pylibmc.Client([ip], binary=False, behaviors={"tcp_nodelay": True, "ketama": True})

tcp.set("key", "1")
tcp.incr("key")
```
The failure stack trace:
```
python /tmp/fu.py 
1.5.2
Traceback (most recent call last):
  File "/tmp/fu.py", line 9, in <module>
    tcp.incr("key")
pylibmc.ClientError: 1 keys failed

```
And an ethernet capture of the sent frames done with Wireshark.:
[pylibmc.pcapng.gz](https://github.com/lericson/pylibmc/files/2282264/pylibmc.pcapng.gz)

The error sent by the server is "CLIENT ERROR: cannot increment or decrement non-numeric values"

**Comment by lericson** [comment]
The error message quite clearly indicates the source of the error: you’re doing incr on a string value!

- Ludvig

**Comment by lericson** [comment]
The documentation was written before Python 3.x support was added, and hence assumes Python 2.x. If you store a bytes object in Python 3.x, it works as intended. The same is likely true for your other encoding problems; pylibmc stores strings as UTF-8 when given Unicode data.

**Comment by Antoine-B2** [comment]
Ok. Thank you

**Comment by lericson** [comment]
I'll keep this open so I remember to update the docs to be clearer on this, thanks for your feedback!

**Comment by hyperair** [comment]
> This doesn't explain why the incr command fails? Unicode is a superset of ASCII, and the numbers 0-128 ave the same meaning in ASCII as they have in Unicode.

I noticed that pylibmc appears to store `unicode` as a pickled value:

```python
pylibmc.Client(['localhost:11212']).set('asdf', u'asdf')  # python2
```

```sh
$ nc -l -p 11212
set asdf 1 0 14
Xasdfq.
```

Earlier versions of python-memcached seemed to do the same too, but stopped after https://github.com/linsomniac/python-memcached/commit/e1f72daabc011b83a8debb86e9e2b7ff6307a41c.

**Comment by lericson** [comment]
> Earlier versions of python-memcached seemed to do the same too, but stopped after [linsomniac/python-memcached@e1f72da](https://github.com/linsomniac/python-memcached/commit/e1f72daabc011b83a8debb86e9e2b7ff6307a41c).

This is exactly why we went for this if I recall correctly. It would be really good to update to reflect python-memcached.
