### ISSUE TITLE
python3 -> python2 without flushing results in pickle errors

### ISSUE THREAD

**Issue by seanbudd** [lericson/pylibmc#235]
When getting a pickled object from the memcached server after going from python3 to python2 I get the following error. 

`ValueError: unsupported pickle protocol: 4`

Would it be worth creating a PR that allows you to set the pickle protocol number?

**Comment by lericson** [comment]
I think it may be worthwhile to have a compile-time flag for pickle protocol version, but only if it is minimally invasive. There is already custom serializers I think?

- Ludvig

**Comment by seanbudd** [comment]
@lericson

I'll prep a PR then and you can let me know what you think. It's a pretty minor bug though, I can't imagine many use cases of a python2 to python3 transition other than with compatibility testing (which is where I encountered this).

**Comment by lericson** [comment]
I’d argue it’s not a bug at all, simply a Python version incompatibility. We used to have a more conservative pickle protocol default version, #216 changed it though. I’m not entirely sure why, but I guess it makes sense to use the most recent version.

**Comment by hyperair** [comment]
If you hope to mix python2 and python3 pylibmc clients on the same memcached server(s), you need to force a pickle protocol of 2 rather than the highest protocol since python2 doesn't support anything higher.

This is a workaround I'm using right now for the purpose.

```python
import functools
import sys

import pylibmc


class MemcachedClient(pylibmc.Client):
    if sys.version_info.major >= 3:
        from pickle import dumps
        pickler = staticmethod(functools.partial(dumps, protocol=2))
        del dumps

        def serialize(self, value):
            # TODO: Include str in this list when pylibmc stops pickling
            # py3 str objects
            if isinstance(value, (bytes, bool, int)):
                return super(MemcachedClient, self).serialize(value)

            return self.pickler(value), (1 << 0)
```

**Comment by lericson** [comment]
Well, I decided to do something about this. The latest master now has a behavior key for this purpose, called `pickle_protocol`. It defaults to -1.
