### ISSUE TITLE
pylibmc cannot find libmemcached

### ISSUE THREAD

**Issue by saschat** [lericson/pylibmc#236]
I am not sure this is a bug or a peculiarity of the system I am using (Ubuntu 16.04 with `libmemcached` 1.0.18 ) but I get the following error was unable to work around it.

```
$ LIBMEMCACHED=/usr/lib/x86_64-linux-gnu pip install pylibmc
$ python -c "import pylibmc"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/.../venv/lib/python3.6/site-packages/pylibmc/__init__.py", line 71, in <module>
    import _pylibmc
ImportError: libmemcached.so.10: cannot open shared object file: No such file or directory
```

Not sure why it insists on `libmemcached.so.10` because the library folder contains
```
$ ls -l /usr/lib/x86_64-linux-gnu/libmemcached*                                                                                                                                                       
-rw-r--r-- 1 0 0 455064 Dec 12  2015 /usr/lib/x86_64-linux-gnu/libmemcached.a
lrwxrwxrwx 1 0 0     22 Dec 12  2015 /usr/lib/x86_64-linux-gnu/libmemcached.so -> libmemcached.so.11.0.0
lrwxrwxrwx 1 0 0     22 Dec 12  2015 /usr/lib/x86_64-linux-gnu/libmemcached.so.11 -> libmemcached.so.11.0.0
-rw-r--r-- 1 0 0 199704 Dec 12  2015 /usr/lib/x86_64-linux-gnu/libmemcached.so.11.0.0
```

I tried to give `pylibmc` a `libmemcached.so.10` by creating a symlink from `libmemcached.so.10` to `libmemcached.so.11` but the error stays.

**Comment by lericson** [comment]
Your pylibmc is built against a different version than what you are giving an address to. Can you check the dynamic linker paths for the _pylibmc SO?

**Comment by saschat** [comment]
How can pylibmc be built against a different version if I specify it with `LIBMEMCACHED=/usr/lib/x86_64-linux-gnu`?

Embarrassingly, I must admit I have not figured out how to check dynamic linker paths. Tools such as `ldd` and `readelf -d` only ever tell me `pylibmc` wants `libmemcached.so.10` but not where it is expecting it. If you know how to check this that would be great!

**Comment by saschat** [comment]
That explains why my symlink experiment failed (I don't have root access and cannot create a `libmemcached.so.10` symlink in the library path). But `libmemcached.so.11` is in the library path. Is there a reason `pylibmc` requires `libmemcached.so.10` and cannot use `libmemcached.so.11`?

**Comment by saschat** [comment]
I manged to get it to work with the python-3.7 environment installed on the system. I guess there is something wrong with the how `pylibmc` was installed in the `python-3.6` environment.

Thanks for all the help and the awesomely quick response time!

Btw. since I managed to get it to work I can say your library is finally available on PythonAnywhere.
