### ISSUE TITLE
different behavior with Python2/Python3 with apache ignite memcache

### ISSUE THREAD

**Issue by mathrb** [lericson/pylibmc#241]
Hello,

I'm facing a different behavior with pylibmc when using it python2 and python3.
The simple code is:
```
import pylibmc
client = pylibmc.Client(["127.0.0.1:11211"], binary=True)
client["key"] = "val"
print(client[b"key"])
```
It connects to a local instance of apache ignite (2.5 in my case).
Using python2, the code works just fine. But using python3, I got this error:
`pylibmc.ConnectionError: error 3 from memcached_set: (43436336) CONNECTION FAILURE, ::rec() returned zero, server has disconnected, host: 127.0.0.1:11211 -> libmemcached/io.cc:456`

Versions:
`python -V
Python 2.7.12`
`python3 -V
Python 3.5.6`

**Comment by lericson** [comment]
Obviously, this is not an issue with pylibmc. Please don't seek support in the bug tracker.
