### ISSUE TITLE
python-memcached FLAG_TEXT == pylibmc FLAG_BOOL

### ISSUE THREAD

**Issue by hyperair** [lericson/pylibmc#242]
In https://github.com/linsomniac/python-memcached/commit/e1f72daabc011b83a8debb86e9e2b7ff6307a41c, python-memcached has assigned `1 << 4` to `_FLAG_TEXT`, which is used for representing `unicode` objects.

However, pylibmc uses the same value for `FLAG_BOOL`. This results in the following oddity:
```python
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
Type "copyright", "credits" or "license" for more information.

IPython 5.5.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pylibmc

In [2]: import memcache

In [3]: servers = ['localhost:11211']

In [4]: mc = memcache.Client(servers)

In [5]: plc = pylibmc.Client(servers)

In [6]: mc.set('asdf', u'asdf')
Out[6]: True

In [7]: plc.get('asdf')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-9372f452b2ee> in <module>()
----> 1 plc.get('asdf')

ValueError: invalid literal for long() with base 10: 'asdf'

In [8]: plc.set('asdf', True)
Out[8]: True

In [9]: mc.get('asdf')
Out[9]: u'1'

In [10]: plc.set('asdf', False)
Out[10]: True

In [11]: mc.get('asdf')
Out[11]: u'0'
```

**Comment by lericson** [comment]
Sigh. How typical. We've used this flag literally for years.

**Comment by lericson** [comment]
I think the best approach here is to implement the python-memcached text stuff, and remove the bool flag. We could have a special case for "is it length 1 and either exactly 0 or 1" to provide backwards compatibility. Ugly, but I don't see an easy way forward.

**Comment by lericson** [comment]
Also... The way pylibmc stores bools is as a one-byte value, and certainly not ASCII encoded. This must mean that the actual value in memcached is 0x00 or 0x01, but python-memcached converts it to u'0' and u'1'?

**Comment by hyperair** [comment]
From past experiences, adding new bitflags downstream should be done from the other side, e.g. `1 << 15` or something (not sure how wide the flag field is). I recall ancient RHEL builds having a similar issue for the open(2) syscall when a very old RHEL kernel was used against a newer Ubuntu userland.

**Comment by hyperair** [comment]
> Also... The way pylibmc stores bools is as a one-byte value, and certainly not ASCII encoded. This must mean that the actual value in memcached is 0x00 or 0x01, but python-memcached converts it to u'0' and u'1'?

Yes

**Comment by lericson** [comment]
Then the workaround would not be too bad -- unlikely that somebody would store just 0x00 or 0x01 as a unicode text.

**Comment by hyperair** [comment]
Actually it turns out that pylibmc stores it as ascii `0` and `1`, sorry.

**Comment by lericson** [comment]
I guess that’s not too unexpected, it’s the same for other types of numbers.

**Comment by hyperair** [comment]
https://github.com/lericson/pylibmc/blob/master/src/_pylibmcmodule.c#L1255

**Comment by lericson** [comment]
This been fixed.
