### ISSUE TITLE
Error: Transport endpoint is not connected

### ISSUE THREAD

**Issue by pyaf** [lericson/pylibmc#251]
Hi, I'm using `pylibmc` for my project which involves a lot of parallel processes each writing some data to the memcache, when I reduce the number of processes things work fine but when I increase the number of processes, I keep getting similar errors like the following:

```
  File "parallel.py", line 523, in <module>
    update_features()
  File "parallel.py", line 323, in update_features
    features = extract_from_mc(features, mc, "edge", "features_edge", 1, len(keypoints)+1)
  File "parallel.py", line 432, in extract_from_mc
    var[str1 + str(index)] = mc.get(str2 + str(index))
pylibmc.Error: error 26 from memcached_get(features_edge1): Transport endpoint is not connected
```

Please let me know if I need to provide extra details. Thanks.

**Comment by lericson** [comment]
This string does not occur in the libmemcached source code. Are you using SASL? Which version of libmemcached? Binary protocol? Etc.

**Comment by pyaf** [comment]
Hi @lericson thanks for your quick response. I'm pretty new to all these. I installed `memcached` version 1.5.6 by apt-get, installed pylibmc with pip. I'm following the default configuration of mc client as mentioned in the [docs](http://sendapatch.se/projects/pylibmc/) as `pylibmc.Client(["127.0.0.1"], binary=True, behaviors={"tcp_nodelay": True,  "ketama": True})`
I need to check for SASL as I don't really know what that is. I'll get back to you soon.

**Comment by pyaf** [comment]
I don't thing I'm using SASL. I've started `memcached` demon using the following command: `memcached -u memcached -d -m 1024 -I 128m -l 127.0.0.1 -p 1111`

**Comment by pyaf** [comment]
I'm indeed using binary protocol. 
Every once in a while, I also get error about bad data chunk, here's a traceback.
```
Traceback (most recent call last):
  File "/home/ags/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/ags/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "multi-processing.py", line 297, in get_features
    mc.set("features_edge%s" % str(edge_index), edgewise_keypoint_features)
pylibmc.ClientError: error 9 from memcached_set: (0x561ecf2c8c40) bad data chunk,  host: 127.0.0.1:1111
Traceback (most recent call last):
  File "multi-processing.py", line 523, in <module>
    update_features()
  File "multi-processing.py", line 323, in update_features
    features = extract_from_mc(features, mc, "edge", "features_edge", 1, len(keypoints)+1)
  File "multi-processing.py", line 432, in extract_from_mc
    var[str1 + str(index)] = mc.get(str2 + str(index))
pylibmc.Error: error 26 from memcached_get(features_edge1): Transport endpoint is not connected
```

**Comment by pyaf** [comment]
I used pymemcache and It worked. I had to handle covert numpy arrays to python lists though as they are not JSON serializable. Thanks @lericson for your help.
