### ISSUE TITLE
Pickle protocol version behavior has no effect

### ISSUE THREAD

**Issue by edelooff** [lericson/pylibmc#252]
I'm working on slowly migrating a project from Python 2 to 3, where access to the same data in the memcached backend is necessary. The release notes for 1.6 state that a new behavior `pickle_protocol` can be used to set the protocol version to one support by both Python 2 and 3. However, this setting appears to have no effect:

```python
>>> import sys
>>> sys.version_info
sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
>>> import pylibmc
>>> pylibmc.__version__
'1.6.0'
>>> mc = pylibmc.Client(servers=['localhost:11211'], behaviors={'pickle_protocol': 2})
>>> mc.get_behaviors()['pickle_protocol']
-1
>>> mc['test'] = {'foo': 'bar'}
```

Reading back the stored value from a Python 2 interpreter:

```python
>>> import sys
>>> sys.version_info
sys.version_info(major=2, minor=7, micro=14, releaselevel='final', serial=0)
>>> import pylibmc
>>> pylibmc.__version__
'1.6.0'
>>> mc = pylibmc.Client(servers=['localhost:11211'], behaviors={'pickle_protocol': 2})
>>> mc.get_behaviors()['pickle_protocol']
-1L
>>> mc['test']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/elmer/devel/ilost/env2/lib/python2.7/site-packages/pylibmc/client.py", line 158, in __getitem__
    value = self.get(key, _MISS_SENTINEL)
ValueError: unsupported pickle protocol: 4
```

Platform wise, this is on a Ubuntu 18.04 Linux machine.

**Comment by edelooff** [comment]
It appears that calling `.set_behaviors()` again with `pickle_protocol` provided does work. Compare:

```python
>>> mc = pylibmc.Client(servers=['localhost:11211'], behaviors={'pickle_protocol': 2})
>>> mc.get_behaviors()['pickle_protocol']
-1
```
```python
>>> mc = pylibmc.Client(servers=['localhost:11211'])
>>> mc.set_behaviors({'pickle_protocol': 2})
>>> mc.get_behaviors()['pickle_protocol']
2
```

**Comment by lericson** [comment]
Hi, this is intended behavior. Glad to hear you could resolve it.

**Comment by lericson** [comment]
Oh and there's an easier way to access the behaviors:

```python
>>> mc = pylibmc.Client(['127.0.0.1:11211'],
                        behaviors={'pickle_protocol': 2})
>>> mc.behaviors['pickle_protocol']
```

**Comment by lericson** [comment]
Oh and you should probably look into the pros and cons of different pickling protocols, they're not all created equal. Typically newer = better in a wider range of cases though, hence the default to use the latest (-1 means "use newest.")

**Comment by edelooff** [comment]
When you say this is intended behavior, I don't quite follow. It's intended that the `pickle_protocol` is accepted and validated when the Client is instantiated, but _not_ used? It seems like a bug (or at least, undocumented behavior) that this behavior can only be affected through `.set_behaviors()`.

To be clear, when I run your code snippet above, I get `-1` as the pickle_protocol.

My workaround works for a raw pylibmc Client that I create myself, but in my actual case, this client is created several layers removed in a session plugin (that I don't control), and not easy to get at.

As for pickling protocols, I'm aware of the version differences, I specifically need version 2 to have cross-compatibilty between Python 2 and 3 :-)

**Comment by lericson** [comment]
Ah, ok. Then that is indeed a bug.

**Comment by lericson** [comment]
In fact I wonder why this is a behavior at all, it's not a libmemcached behavior. Anyway, I'll fix it and add a test.

**Comment by edelooff** [comment]
Thanks for the quick fix and release!
