### ISSUE TITLE
metaget ascii protocol updates

### ISSUE THREAD

**Issue by dormando** [lericson/pylibmc#253]
Yo! I'm poking around for actively development memcached clients looking for some feedback for ASCII protocol changes in the server. Yeah I'm spamming a bit but I believe pretty strongly in these changes :)

memcached/memcached#484 - I've been developing on this for a while. I'm personally happy with the general approach and the code is at the 90% mark. What I'd love to hear now is some feedback from client authors/maintainers on how good/bad/annoying this would be to implement.

I can clear up/rewrite text/add examples if it's not clear enough right now. The protocol is low level, and I'd expect a raw-ish interface from clients. Most users will only be needing a couple of high level patterns, which should be easy to implement wrapping the raw protocol (a herd-protected get, stale-while-revalidate, etc). I haven't written these examples up explicitly yet while I look for feedback.

Thanks!

**Comment by lericson** [comment]
Seems less interesting to production systems and more interesting as debug tooling, or perhaps instrumentation. At any rate, it'd be implemented in libmemcached first, then pylibmc -- so we'd not consume the memcached API immediately.
