### ISSUE TITLE
Add support to TLS

### ISSUE THREAD

**Issue by moisesguimaraes** [lericson/pylibmc#255]
Since version 1.5.13, Memcached [supports TLS][1].

### Motivation

At [OpenStack][2], we are considering a switch from python-memcached to pylibmc in our [oslo.cache][3] Memcache backend driver. In the next step, we will need to enable TLS in Memcached as data must be encrypted in the wire for our scenario.

I looked over the documentation and couldn't find anything related to TLS support. If there is a way to achieve that, please let us know.

I would like to help with the implementation of this if needed.

[1]: https://github.com/memcached/memcached/wiki/TLS
[2]: https://www.openstack.org/
[3]: https://opendev.org/openstack/oslo.cache

**Comment by lericson** [comment]
This is really not something pylibmc can solve, only libmemcached. If libmemcached exposes the feature, we can implement it.

**Comment by moisesguimaraes** [comment]
Thanks @lericson, I'm trying to push this in many fronts, I'm talking to libmemcached folks already. I'll post here any updates to this matter.
