### ISSUE TITLE
Can't install with setuptools >= 52

### ISSUE THREAD

**Issue by fschulze** [lericson/pylibmc#267]
``ImportError: cannot import name 'main' from 'setuptools.command.easy_install'``

**Comment by lericson** [comment]
This seems like a bug elsewhere in your system. We never mention easy_install at all. Or setuptools for that matter.

**Comment by fschulze** [comment]
I hit another problem and through that found out that it is caused by using zc.buildout together with the changes in recent setuptools releases. Sorry for the false alarm.
