### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [lericson/pylibmc#268]
Problem
---------
On aarch64, ‘pip install pylibmc’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, ‘pip install pylibmc’ should download the wheels from pypi

@lericson  Please let me know your interest in releasing aarch64 wheels. I can help in this.

**Comment by odidev** [comment]
@lericson, do you have any plan to release Linux AArch64 wheels. I can help in this.

**Comment by lericson** [comment]
Yes, please! Will they work on macOS do you think?

**Comment by lericson** [comment]
Thanks man, this was fixed.
