### ISSUE TITLE
Travis not running on pull requests

### ISSUE THREAD

**Issue by timgraham** [lericson/pylibmc#272]
The last pull request that shows "1 check passing" is https://github.com/lericson/pylibmc/pull/250 (Aug 15, 2019).

https://travis-ci.org/lericson/pylibmc shows some more recent builds, but it also says "Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on."

**Comment by asherf** [comment]
I have created https://github.com/lericson/pylibmc/pull/274 since GH actions is free for open source projects.

**Comment by lericson** [comment]
Fixed
