### ISSUE TITLE
Text Protocol is vulnerable to command injection

### ISSUE THREAD

**Issue by xhzeem** [lericson/pylibmc#282]
Hi,
I'm a security researcher currently doing research on Memcached wrappers vulnerabilities. 
I found research while back in 2014 which identified that text protocol is vulnerable to command injection, and while testing I found that this still applies to the latest version...

https://www.blackhat.com/docs/us-14/materials/us-14-Novikov-The-New-Page-Of-Injections-Book-Memcached-Injections-WP.pdf

The bug arises when a user-supplied input is passed to the method like `get` which can be used to inject more commands like the following example:
```python
import pylibmc

# Binary is safe because body length is calculated in header.
mcbin = pylibmc.Client(["127.0.0.1"], binary=True)
mcbin.set("xhzeem", "binary")
mcbin.get(b"xhzeem")

# Text
# Vulnerable
mctxt = pylibmc.Client(["127.0.0.1"], binary=False)
mctxt.set("xhzeem", "text")
mctxt.get(b"foo\r\nset xhzeem 0 100 8\r\ninjected") #injected
```

A fix should be applied to check if a key has any `\s` character, and replace it with something or block the request with this behavior.

**Comment by lericson** [comment]
Hi,

This is enabled through a behavior called `verify_keys`,

```
>>> mctxt = pylibmc.Client(["127.0.0.1"], binary=False, behaviors={'verify_keys': True})
>>> mctxt.get(b"foo\r\nset xhzeem 0 100 8\r\ninjected")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
pylibmc.BadKeyProvided: error 33 from memcached_get(foo
set xhzeem 0 100 8
injecte): (0x7fe3ddc497e0) A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE, Key provided had invalid character. -> /Users/lericson/devel/src/libmemcached/src/libmemcached/key.cc:73
```

Thank you for your concern.
