### ISSUE TITLE
Installation problem: `ValueError: invalid mode: 'U'`

### ISSUE THREAD

**Issue by fabiocaccamo** [lericson/pylibmc#284]
Hi, 
I'm installing `pylibmc` (as dependency of [pymemcache](https://github.com/pinterest/pymemcache)) on a fresh local `Python 3.11` virtualenv and during the installation process I receive the following error:

<img width="1162" alt="Screenshot 2022-12-06 at 10 42 44" src="https://user-images.githubusercontent.com/1035294/205875982-971006ea-115a-481f-8034-a787cb505632.png">

**Comment by lericson** [comment]
pylibmc 1.6.1 is outdated, so if you want to use Python 3.11 you need a newer version (like 1.6.3.)

**Comment by fabiocaccamo** [comment]
@lericson thank you for the quick feedback.

**Comment by lericson** [comment]
Happy to help!
