### ISSUE TITLE
doesn't detect memcached failure

### ISSUE THREAD

**Issue by theflow** [lericson/pylibmc#32]
I'm using pylibmc 1.1.1 with libmemcached 1.4.7 and trying to get failure detection to work. This is how I configure pylibmc:

```
    master = pylibmc.Client(hosts, binary=False)
    master.behaviors = {
        "tcp_nodelay": False,
        "ketama": True,
        "failure_limit": 2,
        "_retry_timeout": 30,
        "_auto_eject_hosts": True
    }

    self.pool = pylibmc.ThreadMappedPool(master)
```

when I configure it with two hosts, do a few requests and shut down one of them I get this exception:

MemcachedError: error 35 from memcached_get: SERVER IS MARKED DEAD

for all following requests. I expected it to get ejected and consequent requests would go the other configured memcached instance.

Am I doing something wrong or this is a bug? I can get the behavior I want with the Ruby and PHP libmemcached clients.

thanks,
Florian

**Comment by eduardolujan** [comment]
Hi @lericson Do you know which version solves the problem ?
