### ISSUE TITLE
pylibmc and ketama/failover support

### ISSUE THREAD

**Issue by amcfague** [lericson/pylibmc#80]
I am having issues when either (a) a server is not available at startup or (b) a server drops during a connection.  According to the documentation of both `libmemcached` and `pylibmc`, setting `remove_failed=1` and `ketama=True` in behaviors should enable fail-over should one of the servers go down in a cluster of hosts, while still allowing keys to go to a non-down host.

However, I am not seeing that at all.  When I have a node down at start-up, I get:

```
Exception: error 5 from memcached_set: WRITE FAILURE
```

When it goes down in the middle of writes, I get:

```
Exception: error 3 from memcached_set: CONNECTION FAILURE
```

My question is: is fail-over supported at all?  And if not, does it rest on libmemcached or pylibmc to fix?

Thank you!

Specs:
- Ubuntu 11.10 (64-bit)
- libmemcached 1.0.4
- pylibmc 1.2.2

**Comment by jamescarr** [comment]
Did failover here ever get resolved?

**Comment by lericson** [comment]
The current sad state of affairs is that no useful failover works at all. Really the biggest issue in this project right now. Needs to be fixed in libmemcached. 

-Ludvig

**Comment by lericson** [comment]
Alright, I take that back! It actually does work fairly well, and I have documented this very, very thoroughly  in [the documentation on failover](http://sendapatch.se/projects/pylibmc/behaviors.html#failover). It turns out that modulo distribution is poorly implemented, it's possible to achieve meaningful failover with ketama.

**Comment by kipkoan** [comment]
I am using pylibmc 1.5.0 & libmemcached 1.0.18, and failover is not working for me.  I get:

```ConnectionError: error 3 from memcached_get(splunk|environment-health-tests-): (0x7f8c7b1ccf10) CONNECTION FAILURE,  host: localhost:11213 -> libmemcached/get.cc:314```

I have memcached running locally on port 11211, which is also in the list of memcached servers I'm giving to the pylibmc Client.  If I remove all but the valid host:port then everything works fine.  I am expecting adding the invalid host:ports would have pylibmc remove them as "failed" and use the valid host:port that is up and working.

Can you let me know if this functionality is supposed to work, and what I might be doing wrong if so?  Thank you!

**Comment by lericson** [comment]
What are your behavior configurations, @kipkoan?

**Comment by kipkoan** [comment]
My behavior configuration is:

```MEMCACHED_BEHAVIORS = {
    'ketama': True,
    'remove_failed': 1,
    'retry_timeout': 1,
    'dead_timeout': 60
    }```

(sorry, I should have included that in my previous comment)

**Comment by lericson** [comment]
Here's what I get when I use your settings with only two servers, one "failing" and one working -- I also changed the `dead_timeout = 2` and have a 200 ms sleep between each line of output. As you can see, the failover behavior works quite admirably here-- 

```
~/devel/pylibmc git:master % python tmp/test_failover.py
pylibmc 1.5.0 for libmemcached 1.0.18 (compression=True, sasl=True)
set('a', 'value for a') => ConnectionError('error 3 from memcached_set: (0x7fd2c9e010b0) CONNECTION FAILURE(Connection refused),  host: 127.0.0.1:11212 -> libmemcached/connect.cc:156',)
set('a', 'value for a') => ServerDead('error 35 from memcached_set: (0x7fd2c9e010b0) SERVER IS MARKED DEAD,  host: 127.0.0.1:11212 -> libmemcached/connect.cc:696',)
set('a', 'value for a') => True
set('b', 'value for b') => True
set('b', 'value for b') => True
set('b', 'value for b') => True
set('c', 'value for c') => True
set('c', 'value for c') => True
set('c', 'value for c') => True
set('d', 'value for d') => True
set('d', 'value for d') => True
set('d', 'value for d') => True
set('e', 'value for e') => True
set('e', 'value for e') => True
set('e', 'value for e') => ConnectionError('error 3 from memcached_set: (0x7fd2c9e010b0) CONNECTION FAILURE(Connection refused),  host: 127.0.0.1:11212 -> libmemcached/connect.cc:156',)
set('f', 'value for f') => True
set('f', 'value for f') => True
set('f', 'value for f') => True
set('a', 'value for a') => ServerDead('error 35 from memcached_set: (0x7fd2c9e010b0) SERVER IS MARKED DEAD,  host: 127.0.0.1:11212 -> libmemcached/connect.cc:696',)
set('a', 'value for a') => True
set('a', 'value for a') => True
set('b', 'value for b') => True
set('b', 'value for b') => True
set('b', 'value for b') => True
set('c', 'value for c') => True
set('c', 'value for c') => True
set('c', 'value for c') => True
set('d', 'value for d') => True
set('d', 'value for d') => ConnectionError('error 3 from memcached_set: (0x7fd2c9e010b0) CONNECTION FAILURE(Connection refused),  host: 127.0.0.1:11212 -> libmemcached/connect.cc:156',)
set('d', 'value for d') => ServerDead('error 35 from memcached_set: (0x7fd2c9e010b0) SERVER IS MARKED DEAD,  host: 127.0.0.1:11212 -> libmemcached/connect.cc:696',)
set('e', 'value for e') => True
set('e', 'value for e') => True
set('e', 'value for e') => True
set('f', 'value for f') => True
set('f', 'value for f') => True
set('f', 'value for f') => True
set('a', 'value for a') => True
set('a', 'value for a') => True
set('a', 'value for a') => True
set('b', 'value for b') => True
set('b', 'value for b') => True
set('b', 'value for b') => True
set('c', 'value for c') => True
set('c', 'value for c') => True
set('c', 'value for c') => True
set('d', 'value for d') => ConnectionError('error 3 from memcached_set: (0x7fd2c9e010b0) CONNECTION FAILURE(Connection refused),  host: 127.0.0.1:11212 -> libmemcached/connect.cc:156',)
set('d', 'value for d') => ServerDead('error 35 from memcached_set: (0x7fd2c9e010b0) SERVER IS MARKED DEAD,  host: 127.0.0.1:11212 -> libmemcached/connect.cc:696',)
set('d', 'value for d') => True
set('e', 'value for e') => True
set('e', 'value for e') => True
set('e', 'value for e') => True
set('f', 'value for f') => True
set('f', 'value for f') => True
set('f', 'value for f') => True
set('a', 'value for a') => True
set('a', 'value for a') => True
set('a', 'value for a') => True
set('b', 'value for b') => True
set('b', 'value for b') => ConnectionError('error 3 from memcached_set: (0x7fd2c9e010b0) CONNECTION FAILURE(Connection refused),  host: 127.0.0.1:11212 -> libmemcached/connect.cc:156',)
set('b', 'value for b') => ServerDead('error 35 from memcached_set: (0x7fd2c9e010b0) SERVER IS MARKED DEAD,  host: 127.0.0.1:11212 -> libmemcached/connect.cc:696',)
set('c', 'value for c') => True
set('c', 'value for c') => True
set('c', 'value for c') => True
set('d', 'value for d') => True
set('d', 'value for d') => True
set('d', 'value for d') => True
set('e', 'value for e') => True
set('e', 'value for e') => True
set('e', 'value for e') => True
set('f', 'value for f') => True
set('f', 'value for f') => True
set('f', 'value for f') => True
set('a', 'value for a') => True
set('a', 'value for a') => ConnectionError('error 3 from memcached_set: (0x7fd2c9e010b0) CONNECTION FAILURE(Connection refused),  host: 127.0.0.1:11212 -> libmemcached/connect.cc:156',)
set('a', 'value for a') => ServerDead('error 35 from memcached_set: (0x7fd2c9e010b0) SERVER IS MARKED DEAD,  host: 127.0.0.1:11212 -> libmemcached/connect.cc:696',)
set('b', 'value for b') => True
set('b', 'value for b') => True
set('b', 'value for b') => True
set('c', 'value for c') => True
set('c', 'value for c') => True
set('c', 'value for c') => True
set('d', 'value for d') => True
set('d', 'value for d') => True
set('d', 'value for d') => True
set('e', 'value for e') => True
set('e', 'value for e') => True
set('e', 'value for e') => True
set('f', 'value for f') => True
set('f', 'value for f') => True
set('f', 'value for f') => True
```

**Comment by lericson** [comment]
I think there might be some confusion on your end as to what the failover does -- it actually triggers exceptions, you see. So maybe you're just seeing the intermittent exceptions and think it's failing all the time? The idea behind this mechanism is to give you an error when the servers go down so you know your memcached cluster isn't firing on all cylinders.

**Comment by kipkoan** [comment]
The only exception I ever get is the ```ConnectionError('error 3 from memcached_set: (0x7fd2c9e010b0) CONNECTION FAILURE``` one.  I never get ```ServerDead('error 35 from memcached_set: (0x7fd2c9e010b0) SERVER IS MARKED DEAD```, and from what I can tell, it never is marked dead, and nothing is ever set in the memcached server that is running & alive (port 11211).  Is my code supposed to handle the ConnectionError exception somehow?  I was thinking that would happen automatically.  Can you give me your ```test_failover.py``` script so I can try the exact same thing?  Thanks for your help Ludvig!

**Comment by lericson** [comment]
```python
import time
import pylibmc

def build_info():
    import _pylibmc
    return ("pylibmc %s for libmemcached %s (compression=%s, sasl=%s)"
            % (pylibmc.__version__,
               _pylibmc.libmemcached_version,
               _pylibmc.support_compression,
               _pylibmc.support_sasl))

print build_info()

mc = pylibmc.Client(['127.0.0.1:11211',
                     '127.0.0.1:11212'])
#mc.behaviors['verify_keys'] = True
#mc.behaviors['ketama'] = True
#mc.behaviors['remove_failed'] = 1
#mc.behaviors['dead_timeout'] = 5
#mc.behaviors['retry_timeout'] = 1
mc.behaviors = {
'ketama': True,
'remove_failed': 1,
'retry_timeout': 1,
'dead_timeout': 2
}


keyspace = 'aaabbbcccdddeeefff'
n_ops = len(keyspace)*5

d = pylibmc.ThreadMappedPool(mc)

for i in xrange(n_ops):

    with d.reserve() as mc:

        key = keyspace[i % len(keyspace)]
        value = 'value for {}'.format(key)

        print 'set({!r}, {!r}) =>'.format(key, value),

        try:
            print '\x1b[32m{!r}\x1b[0m'.format(mc.set(key, value))
        except pylibmc.Error as e:
            print '\x1b[31m{!r}\x1b[0m'.format(e)

        mc.disconnect_all()
        mc = mc.clone()

    time.sleep(0.2)
```

**Comment by lericson** [comment]
Interestingly, if I do `mc = mc.clone()`, I get your error. It seems cloning resets the retry states. Also a sane client shouldn't be doing `disconnect_all` like that, but this script was actually to try the failover behavior that Django should be producing.

**Comment by kipkoan** [comment]
Ludvig - your code helped me see what I was doing wrong.  I wasn't putting the memcached calls into a try-except block.  Thank you again for all your help.

**Comment by lericson** [comment]
You probably shouldn't, either!

**Comment by kipkoan** [comment]
I'm not using Django, just a stand-alone application.  If I put it in the try-except block (like your script) it works as expected.  If I change your script to take the "mc.set" call out of the try-except block, it fails the same way I was experiencing in my app.

**Comment by lericson** [comment]
Aha I see! How does it handle the exception otherwise?
